/**
 * Backfill vendors.area from postcodes.io.
 *
 * Listings store an outward code ("E8", "SW11"), not a full postcode, so this
 * resolves per distinct outcode — a few dozen requests for the whole catalogue
 * instead of one per vendor.
 *
 * Two steps per outcode, and the second one matters: /outcodes/{code} returns
 * every borough the outcode touches, but that list is ALPHABETICAL, not ordered
 * by coverage. Taking the first entry gives W2 -> Ealing and SE15 -> Lewisham,
 * both wrong (they are Westminster and Southwark). So we take the outcode's
 * centroid and reverse-geocode that point, which yields the borough the outcode
 * actually sits in.
 *
 * Idempotent: only touches rows where area is null.
 */
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";

for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z_]+)=(.*)$/);
  if (m) process.env[m[1]] ||= m[2].trim();
}

// Writes to vendors require the service role. With the anon key RLS silently
// blocks every update and returns no error, so the script reports success
// having changed nothing — refuse to run rather than lie.
if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
  console.error("SUPABASE_SERVICE_ROLE_KEY is required — the anon key cannot update vendors.");
  console.error("Run with --emit-sql to print the statements instead, and apply them yourself.");
  if (!process.argv.includes("--emit-sql")) process.exit(1);
}

const EMIT_SQL = process.argv.includes("--emit-sql");
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
);

const { data: rows, error } = await supabase
  .from("vendors")
  .select("id, base_postcode")
  .is("area", null)
  .not("base_postcode", "is", null);

if (error) { console.error("fetch failed:", error.message); process.exit(1); }

// The stored value may be a full postcode or just the outward code.
const outcodeOf = (pc) => pc.trim().toUpperCase().split(/\s+/)[0];
const outcodes = [...new Set(rows.map((r) => outcodeOf(r.base_postcode)))];
console.log(`${rows.length} vendors across ${outcodes.length} distinct outcodes`);

// 1. Centroid per outcode.
const centroids = [];
for (const code of outcodes) {
  try {
    const res = await fetch(`https://api.postcodes.io/outcodes/${encodeURIComponent(code)}`);
    if (!res.ok) { console.warn(`  ${code}: HTTP ${res.status}`); continue; }
    const { result } = await res.json();
    if (result?.latitude != null && result?.longitude != null) {
      centroids.push({ code, latitude: result.latitude, longitude: result.longitude });
    }
  } catch (err) {
    console.warn(`  ${code}: ${err.message}`);
  }
}

// 2. Reverse-geocode each centroid to the borough it actually falls in.
const areaByOutcode = new Map();
for (let i = 0; i < centroids.length; i += 100) {
  const batch = centroids.slice(i, i + 100);
  const res = await fetch("https://api.postcodes.io/postcodes", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      geolocations: batch.map(({ longitude, latitude }) => ({ longitude, latitude })),
    }),
  });
  if (!res.ok) { console.warn(`  reverse batch ${i}: HTTP ${res.status}`); continue; }
  const { result } = await res.json();
  batch.forEach((c, j) => {
    const area = (result[j]?.result || [])[0]?.admin_district;
    if (area) areaByOutcode.set(c.code, area);
  });
}
console.log(`resolved ${areaByOutcode.size}/${outcodes.length} outcodes`);

if (EMIT_SQL) {
  console.log("\n-- generated by scripts/backfill-areas.mjs");
  for (const [code, area] of areaByOutcode) {
    console.log(
      `update public.vendors set area = '${area.replace(/'/g, "''")}' ` +
      `where area is null and upper(split_part(base_postcode,' ',1)) = '${code}';`,
    );
  }
  process.exit(0);
}

let updated = 0;
for (const [code, area] of areaByOutcode) {
  const ids = rows.filter((r) => outcodeOf(r.base_postcode) === code).map((r) => r.id);
  // select() so the response carries the affected rows — without it a
  // policy-blocked update returns no error and no indication it did nothing.
  const { data: changed, error: upErr } = await supabase
    .from("vendors").update({ area }).in("id", ids).select("id");
  if (upErr) { console.error(`  ${code}: ${upErr.message}`); continue; }
  updated += (changed || []).length;
}

console.log(`done — ${updated} of ${rows.length} updated`);
if (updated === 0 && rows.length > 0) {
  console.error("NOTHING WAS WRITTEN — check credentials and RLS.");
  process.exit(1);
}
